# MOD keys
$MOD1 = SHIFT
$MOD2 = CTRL
$MOD3 = SUPER
$MOD4 = ALT
 
$mainMod = $MOD3

# Environment variables
source = ~/.config/hypr/conf/env_var.conf
source = ~/.config/hypr/conf/env_var_nvidia.conf # NVIDIA needs some specific envvars idk why

# Default apps and slightly more elaborate commands
source = ~/.config/hypr/conf/apps.conf
source = ~/.config/hypr/conf/essentials.conf

# Monitors
source = ~/.config/hypr/conf/monitors.conf
## Lock workspace 1 to main monitor
workspace = 1, monitor:$mainMonitor # monitor:DP-1

# Set system dark theme
exec-once = ~/.config/hypr/scripts/dark-theme

# Input configuration (Mouse and Keyboard mostly)
source = ~/.config/hypr/conf/input.conf

# Launch apps
source = ~/.config/hypr/conf/launch.conf

# Styling
source = ~/.config/hypr/conf/styling.conf

# Window and Layer rules
source = ~/.config/hypr/conf/windowrules.conf

# Keybinds and the essential commands defitions
source = ~/.config/hypr/conf/keybinds.conf

