# Variables for default applications efault applications

$terminal = alacritty
$fileExplorer = alacritty -e yazi
$appLauncher = wofi
$commandLauncher = wofi --show run
$clipboard = cliphist list | wofi -dmenu | cliphist decode | wl-copy
$logoutMenu = wlogout --protocol layer-shell
$notificationManager = mako
$bluetoothManager = blueman-applet
$networkManager = nm-applet --indicator
$musicPlayer = vlc # TODO: ffffffuuuck i can't find a decent music player
