# Screenshots
## Screenshot main screen
$ScreenshotMainMonitor = grim -g "0,0 1920x1080" - | swappy -f -
## Screenshot secondary monitor
$ScreenshotSecondaryMonitor =grim -g "1920,0 1920x1080" - | swappy -f - # Screenshot secondary monitor
## Screenshot selected area
$ScreenshotSelection = grim -g "$(slurp)" - | swappy -f -

# Session management
$LockScreen = swaylock
$ShowLogoutMenu = wlogout --protocol layer-shell

# Background processes
## Bar management
# The current bar used in this setup is waybar.
# There are some complex mechanisms to set it up, see ~/.config/waybar/readme.md
$LaunchAndBindBar = ls ~/.config/waybar/conf/* | entr -s ". ~/.config/waybar/scripts/build-config.sh"
$LaunchBar = ~/.config/waybar/scripts/launch-waybar.sh

## Clipboard
$SetClipboardTracker = wl-paste --watch cliphist store