# Keybinds

# General

## Launch Apps
bind = $MOD4, Q, exec, $terminal
bind = $MOD4, E, exec, $fileExplorer
bind = $MOD4, SPACE, exec, $appLauncher
bind = $mainMod, D, exec, $commandLauncher
bind = $mainMod, V, exec, $clipboard

## Manage Session
bind = $MOD4 $MOD1, M, exit, # Force quit hyprland.
bind = $MOD4, M, exec, $ShowLogoutMenu
bind = $MOD4, L, exec, $LockScreen
bind = $MOD4 $MOD1, R, exec, hyprctl reload

## Screenshots
bind = $MOD4, S, exec, $ScreenshotSelection
bind = $MOD1, PRINT, exec, $ScreenshotSelection
bind = $MOD2 $MOD4, S, exec, $ScreenshotMainMonitor
bind = , PRINT, exec, $ScreenshotMainMonitor
bind = $MOD2 $MOD4 $MOD1, S, exec, $ScreenshotSecondaryMonitor

# Windows and Workspaces

## Reposition and restyle
bind = $MOD4, F4, killactive, # Close the active window
bind = $MOD4, V, togglefloating, # Toggle floating for focused window
bind = $MOD4, P, pseudo, # dwindle
# TODO: Togglesplit stopped working
# bind = $MOD4, J, togglesplit, # dwindle
bindm = $mainMod, mouse:272, movewindow # Move window, mouse:272 = left click
bindm = $mainMod, mouse:273, resizewindow # Resize window, mouse:273 = right click

## Move focus with mainMod + arrow keys or hjkl
bind = $mainMod, left, movefocus, l
bind = $mainMod, h, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, l, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, k, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, j, movefocus, d

## Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

## Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod $MOD1, 1, movetoworkspace, 1
bind = $mainMod $MOD1, 2, movetoworkspace, 2
bind = $mainMod $MOD1, 3, movetoworkspace, 3
bind = $mainMod $MOD1, 4, movetoworkspace, 4
bind = $mainMod $MOD1, 5, movetoworkspace, 5
bind = $mainMod $MOD1, 6, movetoworkspace, 6
bind = $mainMod $MOD1, 7, movetoworkspace, 7
bind = $mainMod $MOD1, 8, movetoworkspace, 8
bind = $mainMod $MOD1, 9, movetoworkspace, 9
bind = $mainMod $MOD1, 0, movetoworkspace, 10

## Move workspaces between monitors
bind = $mainMod $MOD2, 1, movecurrentworkspacetomonitor, 1
bind = $mainMod $MOD2, 2, movecurrentworkspacetomonitor, 0 # Not sure why HDMI-1's id is 0 tho wtf

## Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1
