# Launch applications on start up

# Necessary background processes

## XDG Portals
exec-once = ~/.config/hypr/scripts/xdg-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

## Fcitx
# This was useful for composing inputs, such as inserting foreign characters or emojis
# TODO: FCITX, I gave up setting it up, might come back to it one day
# exec-once = fcitx5 --replace -d


## Wallpaper manager
exec-once = awww-daemon

## Top and bottom bars
exec-once = $LaunchAndBindBar
exec = $LaunchBar

exec-once = $notificationManager
exec-once = $bluetoothManager
exec-once = $networkManager
exec-once = $SetClipboardTracker

# Personal apps that I like to run at launch
# TODO: I'm not really using any of this, should I even keep these?
## Obsidian
# exec-once = [workspace 9; monitor $secondaryMonitor] obsidian 

## Funky Workspace
### Todo List
# exec-once = [workspace 8; monitor $secondaryMonitor;] alacritty -e nvim ~/todo.txt

### Music Player
# exec-once = [workspace 8; monitor HDMI-1] $music_player --no-playlist-autostart ~/musicas
