# Windowrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

## Floating windows
windowrule = float 1, match:class org.pulseaudio.pavucontrol # Pavucontrol
windowrule = float 1, match:class ^blueman-manager$ # Bluetooth
windowrule = float 1, match:class ^(nm-connection-editor)$ # Network manager
windowrule = float 1, match:title ^(btop)$ # Btop
windowrule = float 1, match:class ^(org.gnome.Loupe)$ # Image viewer
windowrule = float 1, match:class ^((?i)thunar)$, match:title negative:^(.* - Thunar)$ # Thunar windows float 1 except for the main app. Rename and confirmation windows for example.
windowrule = float 1, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float 1, match:class ^(org.gnome.FileRoller) # Extrair e compactar arquivos
windowrule = float 1, match:class ^(viewnior)$

## Steam
windowrule = float 0, match:class ^(steam)$, match:title ^(Steam)$
windowrule = center 1, match:class ^(steam)$, match:title ^(.+)$

## Position pavucontrol on topright
windowrule = move 100%-w-11 47, match:class org.pulseaudio.pavucontrol

## Tkinter apps
windowrule = center 1, match:class Tk
windowrule = center 1, match:class Toplevel

# Layer rules
## I'm not really sure why these count as different but sure whatever
layerrule = dim_around on, match:namespace wofi
