#!/bin/bash
if [[ $(pactl get-default-sink) == "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1" ]]; then
	pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo
else
	pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo-extra1
fi

