#!/usr/bin/env bash

# Original script by @speltriao on GitHub
# https://github.com/speltriao/Pacman-Update-for-GNOME-Shell

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi

# Calculate updates for each service
AUR=$(yay -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)
COUNT=$((OFFICIAL+AUR))

if [[ "$COUNT" = "0" ]]
then
    echo ""
else
    # This Update symbol is RTL. So &#x202d; is left-to-right override.
    echo " $COUNT"
fi
exit 0
