#! /bin/bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll="ls -la"
alias la="ls -a"
alias upd="sudo pacman -Syu"

# Usage: yt-dlp-mp3 <url>
alias yt-dlp-mp3="yt-dlp -x --audio-format mp3 --embed-thumbnail -o '%(uploader)s - %(title)s' --add-metadata"
# Usage: yt-dlp-playlist <file_name>
# file_name consists of multiple lines each being a single url to be downloaded
alias yt-dlp-playlist="yt-dlp -x --audio-format mp3 --embed-thumbnail -o '%(uploader)s - %(title)s' -a"

# Usage: Copy the qrcode into cliboard then run `otpappend <name>`
# <name> must be an existing file in the password store vault
otpappend() {
  wl-paste | zbarimg -q --raw - | pass otp append $1;
  pass otp -c $1;
}

# alias otpappend="wl-paste | zbarimg -q --raw - | pass otp append "

# Command for disabling laptop main keyboard
alias dk="hyprctl eval \"hl.device({ name = 'at-translated-set-2-keyboard', enabled = false })\""

alias pacfind="pacman -Q | grep"

# Function for changing directory and listing the target content
# Not sure why this couldn't just be an alias
cdd() { cd "$@"; }
cs() { builtin cd "$@" && ls; }
alias cd=cs

# Set envs for specific apps that fuck up XDG architecture
alias adb='HOME="$XDG_DATA_HOME"/android adb'
alias nvidia-settings="nvidia-settings --config='$XDG_CONFIG_HOME'/nvidia/settings"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
