#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load starship
eval "$(starship init bash)"

# Aliases
if [ -f $HOME/.bash_aliases ]; then
	. $HOME/.bash_aliases
fi

# Autocomplete
if [ -f $HOME/.bash_autocomplete ]; then
    . $HOME/.bash_autocomplete
fi


# Environment Variables
if [ -f $HOME/.bash_venv ]; then
    . $HOME/.bash_venv
fi

